package fi.metropolia.practisecalorie.data;

import androidx.annotation.NonNull;
import androidx.room.Entity;
import androidx.room.PrimaryKey;

import java.time.LocalDate;

@Entity
public class Food {

    @PrimaryKey(autoGenerate = true)
    private long id;
    private final LocalDate day;
    private final String foodName;
    private final double kcalPerPortion;
    private final double portion;
    private final double totalKcalPerEntry;

    private int userID;

    /**
     * creates an object food with listed parameters
     * @param day is when the user creates the food
     * @param foodName food name set byy the user
     * @param kcalPerPortion food's caloric information
     * @param portion user's intake
     * @param totalKcalPerEntry is calculated after user enters food's caloric information
     * @param userID auto generated by the program
     */
    public Food(LocalDate day, String foodName, double kcalPerPortion, double portion, double totalKcalPerEntry, int userID) {
        this.day = day;
        this.foodName = foodName;
        this.kcalPerPortion = kcalPerPortion;
        this.portion = portion;
        this.totalKcalPerEntry = totalKcalPerEntry;
        this.userID = userID;

    }

    /**
     * food's id
     * @param id is food id generated by the app
     */
    public void setId(long id) {
        this.id = id;
    }

    /**
     * gets the food's id
     * @return food's id
     */
    public long getId() {
        return id;
    }

    /**
     * gets the date when food is created
     * @return day when food was created
     */
    public LocalDate getDay() {
        return day;
    }

    /**
     * get the food's name
     * @return food's name
     */
    public String getFoodName() {
        return foodName;
    }

    /**
     * gets kcal info a food per 100 gram
     * @return kcal of the food per 100 gram
     */
    public double getKcalPerPortion() {
        return kcalPerPortion;
    }

    /**
     * gets the portion of the food entered by the user
     * @return portion of the food
     */
    public double getPortion() {
        return portion;
    }

    /**
     * gets the total kcal of the entry
     * @return total kcal of the entry
     */
    public double getTotalKcalPerEntry() {
        return totalKcalPerEntry;
    }

    /**
     * gets the userID
     * @return userID
     */
    public int getUserID() {
        return userID;
    }

    /**
     * setting an ID for the logged user
     * @param userID userID
     */
    public void setUserID(int userID) {
        this.userID = userID;
    }

    @NonNull
    @Override
    public String toString() {
        return "Food{" +
                "id=" + id +
                ", day=" + day +
                ", foodName='" + foodName + '\'' +
                ", kcalPerPortion=" + kcalPerPortion +
                ", portion=" + portion +
                ", totalKcalPerEntry=" + totalKcalPerEntry +
                '}';
    }
}
